### ISSUE TITLE
Check compatibility with Python 3

### ISSUE THREAD

**Issue by ridnarong** [netpieio/microgear-python#7]
ลองดูว่ารันบน Python 3 ได้หรือเปล่า เพราะ dependency ที่ใช้ อาจจะยังไม่สนับสนุน

**Comment by ridnarong** [comment]
เท่าที่ลองกับ Python 3.4.3 นะเจอปัญหาดังนี้
```
  File "basic.py", line 12
    print "Now I am connected with netpie"
                                         ^
SyntaxError: Missing parentheses in call to 'print'
```
ตรงนี้แก้ได้โดยใส่วงเล็บครอบเวลา print

```
Traceback (most recent call last):
  File "basic.py", line 1, in <module>
    import microgear.client as client
  File "/microgear/microgear/client.py", line 2, in <module>
    from urlparse import urlparse
ImportError: No module named 'urlparse'
```
ตรงนี้ดูเหมือนว่า Python 3 ไม่มี Module `urlparse` แล้ว ไม่รู้ว่าเปลื่ยนชื่อเป็นอะไร หรือใช้อะไรแทน ช่วยดูหน่อยนะ

**Comment by ridnarong** [comment]
หวังว่าจะเก็บหมด 98bcdeaaa9b803969cac2bb79e1070302d6bd9b2
